version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
      POSTGRES_DB: todo
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://todo:todo@db:5432/todo
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ./instance:/app/instance

volumes:
  pg_data: